### ISSUE TITLE
(FEATURE) Add export option from preview tool

### ISSUE THREAD

**Issue by jjxtra** [Auburn/FastNoise#11]
It would be nice to have a save button on the preview tool to export. Being able to specify the size would be very good as well.

The second request is a "make seamless" option. This may not be feasible but sure would be amazing.

**Comment by squishybanana04** [comment]
I haven't found the source code for the preview, but the make seamless option seems easy to implement. I did one here (although it's extremely buggy) [https://github.com/squishybanana04/HeightMapGenerator](https://github.com/squishybanana04/HeightMapGenerator)
