### ISSUE TITLE
Question: Can I make tileable(seamless) textures?

### ISSUE THREAD

**Issue by lazzy07** [Auburn/FastNoise#33]
Can I make tileable(seamless) textures using this library? If so how?

**Comment by eobet** [comment]
Ended up here through an internet search and I have the same question! :)

**Comment by pratikunterwegs** [comment]
Adding this comment to bump the issue up, had the same question.
Seamless textures in FastNoise might help with getting them in the R package [`ambient`](https://github.com/thomasp85/ambient) which is what I really want to use.

**Comment by Auburn** [comment]
FastNoise2 has support for tileable 2D textures using 4D noise. I've looked into adding it for FastNoise (lite) but it is beyond the library's scope
