### ISSUE TITLE
‘zs’ may be used uninitialized in this function

### ISSUE THREAD

**Issue by 1Hyena** [Auburn/FastNoise#37]
warning: ‘zs’ may be used uninitialized in this function [-Wmaybe-uninitialized]

note: ‘zs’ was declared here
     FN_DECIMAL xs, ys, zs;

```C++
FN_DECIMAL FastNoise::SingleValue(unsigned char offset, FN_DECIMAL x, FN_DECIMAL y, FN_DECIMAL z) const
{
    int x0 = FastFloor(x);
    int y0 = FastFloor(y);
    int z0 = FastFloor(z);
    int x1 = x0 + 1;
    int y1 = y0 + 1;
    int z1 = z0 + 1;

    FN_DECIMAL xs, ys, zs; // <-- THIS LINE GIVES WARNING
    switch (m_interp) // BECAUSE THIS SWITCH HAS NO DEFAULT
    {
    case Linear:
        xs = x - (FN_DECIMAL)x0;
        ys = y - (FN_DECIMAL)y0;
        zs = z - (FN_DECIMAL)z0;
        break;
    case Hermite:
        xs = InterpHermiteFunc(x - (FN_DECIMAL)x0);
        ys = InterpHermiteFunc(y - (FN_DECIMAL)y0);
        zs = InterpHermiteFunc(z - (FN_DECIMAL)z0);
        break;
    case Quintic:
        xs = InterpQuinticFunc(x - (FN_DECIMAL)x0);
        ys = InterpQuinticFunc(y - (FN_DECIMAL)y0);
        zs = InterpQuinticFunc(z - (FN_DECIMAL)z0);
        break;
    }

    FN_DECIMAL xf00 = Lerp(ValCoord3DFast(offset, x0, y0, z0), ValCoord3DFast(offset, x1, y0, z0), xs);
    FN_DECIMAL xf10 = Lerp(ValCoord3DFast(offset, x0, y1, z0), ValCoord3DFast(offset, x1, y1, z0), xs);
    FN_DECIMAL xf01 = Lerp(ValCoord3DFast(offset, x0, y0, z1), ValCoord3DFast(offset, x1, y0, z1), xs);
    FN_DECIMAL xf11 = Lerp(ValCoord3DFast(offset, x0, y1, z1), ValCoord3DFast(offset, x1, y1, z1), xs);

    FN_DECIMAL yf0 = Lerp(xf00, xf10, ys);
    FN_DECIMAL yf1 = Lerp(xf01, xf11, ys);

    return Lerp(yf0, yf1, zs);
}
```

**Comment by JohanAR** [comment]
That sounds like an error in your compiler because the switch statement covers all the possible values for m_interp, thus the default-code would be unreachable. In fact, I'm fairly sure clang will give you a warning if you do try adding a default case to it.

**Comment by 1Hyena** [comment]
gcc version 9.3.0 (Arch Linux 9.3.0-1)

There are also missing `// fall through` comments by the way. As a result the the compiler warns about all the implicit fall through cases.

All I'm saying is that this lib would be great if it had these issues fixed. Don't take it personally. I am not saying that the creator of the lib is a bad programmer. I am just giving advice to make this lib more "multicultural" and more tolerant. But sure, feel free to ignore it. I have manually fixed these bugs in my fork of the lib anyway so it doesn't affect me any more.

**Comment by Jachdich** [comment]
I've noticed a lot of similar warnings which are a bit annoying but in no way detract from the usefulness of the library. g++ (gcc) 10.1.0 Manjaro linux54

**Comment by 1Hyena** [comment]
I also used Manjaro btw but I thought it's more informative to just say Arch because Manjaro is Arch with a graphical installer, right? :D

**Comment by Jachdich** [comment]
@1Hyena yeah kinda, but manjaro also had fractionally older packages (so not at all an issue here, IIRC it's about 3 days before manjaro gets them after arch) and there's probably other minor changes but I agree, not worth worrying about tbh.
