### ISSUE TITLE
Standalone FastNoiseLite Preview app

### ISSUE THREAD

**Issue by ghost** [Auburn/FastNoise#50]
Is it possible to make the preview application to run in a self-contained mode without requiring to have the dotnet runtime previously installed ?

**Comment by Auburn** [comment]
It is possible but the exe would be about 60MB

**Comment by 8nouk** [comment]
It would be easier to make it run on Linux systems this way.
Thanks!

**Comment by Auburn** [comment]
I think self contained binaries are only supported by Windows

**Comment by 8nouk** [comment]
I know that Mono can do it. Maybe I wrongly assumed that Dotnet core could too.
