### ISSUE TITLE
C version assumes a C++ compiler

### ISSUE THREAD

**Issue by benob** [Auburn/FastNoise#51]
Some C++ idioms are used in the C version, such as use of bool as type, "true" and "false" as values, the default argument value of fnlCreateState. Fixing those allows compiling with gcc -std=c99.

**Comment by Auburn** [comment]
Thanks for spotting that, should be fixed in https://github.com/Auburn/FastNoise/commit/2fbd2b4ebf0f8735fcdec3bfe5c1e1c6a446dcf4

Let me know if not.

**Comment by benob** [comment]
PrimeX is not declared (I guess the intended constant is PRIME_X)
```
FastNoiseLite.h:1751:31: error: ‘PrimeX’ undeclared (first use in this function)
 1751 |     int x3 = x1 + (int)((long)PrimeX << 1);
```
Also, updating the C example with something that works out of the box would be nice. You could add something like:
```
#include <stdio.h>
#include <stdlib.h>

#define FNL_IMPL
#include "FastNoiseLite.h"

int main() {
...
}
```

**Comment by Auburn** [comment]
Ah, sry about that. I've fixed it now.

Are you talking about the getting started example?

**Comment by benob** [comment]
Yes, the getting started example.
Thanks for the fix.

**Comment by cj09bruno** [comment]
could you please update the C getting started Reame.md file? thanks.
