### ISSUE TITLE
Segmentation fault when using Domain Warp in multi-threaded environment.

### ISSUE THREAD

**Issue by ArneDJ** [Auburn/FastNoise#57]
Hi,

I want to generate a 4K noise image as quick as possible and decided to use multi-threading.
FastNoise works perfectly fine using the standard GetNoise() function in a multi-threaded environment.
But once I try calling the DomainWarp() function my program segfaults. 

Is multi-threading not supported with domain warp in the C++ version?

Thanks in advance.

**Comment by Auburn** [comment]
Sorry for the slow reply. Can you post your code, domain warp should work fine multi-threaded.

**Comment by ArneDJ** [comment]
I managed to fix it. The problem wasn't caused by FastNoise or multi-threading, it was caused by me, I was incorrectly mapping the data into the image.
