### ISSUE TITLE
HLSL file Compilation error 

### ISSUE THREAD

**Issue by chrisch0** [Auburn/FastNoise#59]
Hi, 
I find some compilation errors in hlsl version when using fnlDomainWarp3D(state, x, y, z).
The declaration of the function _fnlSingleDomainWarpBasicGrid3D and _fnlSingleDomainWarpOpenSimplex2Gradient doesn't match the implement. The argument modifier of 'zp' and 'zr' should be 'inout'

The switch statements in function _fnlTransformDomainWarpCoordinate3D(state, x, y, z) missing 'break;' in the default statement.

**Comment by Auburn** [comment]
I think this was fixed in 0cedc661ac299ba002f92e20851035a1d78869c0
Let me know if not
