### ISSUE TITLE
range of distances for cellular noise

### ISSUE THREAD

**Issue by malytomas** [Auburn/FastNoise#60]
I am updating fastnoise from eb126aaadff4359614fe676f782f47b79c0877a7 to 0cedc661ac299ba002f92e20851035a1d78869c0 and I have noticed that the range of values returned for distance of cellular noise has changed.
It used to return non-negative values, typically in range (0 .. 1). But I see values mostly in (-1 .. 0) now.
Is this change intentional? Can you, please, comment what is the expected range now?
Thanks

**Comment by Auburn** [comment]
It was intentional and part of the FastNoise Lite changes. The new fractal types rely on the noise types returning values between -1 and 1, so this change was made to bring cellular distance noise into the same range as other noise types.
