### ISSUE TITLE
FNL_FRACTAL_DOMAIN_WARP_INDEPENDENT

### ISSUE THREAD

**Issue by Lua200** [Auburn/FastNoise#61]
I would like to set the Domain Warp Fractal to "Domain Warp Independent".

Is this the correct way?

      fnl_state noise = fnlCreateState();
      noise.fractal_type = FNL_FRACTAL_DOMAIN_WARP_INDEPENDENT;
      noise.domain_warp_type = FNL_DOMAIN_WARP_OPENSIMPLEX2;

Thanks in advance! :)

**Comment by Auburn** [comment]
Yes, please don't post questions as github issues. Join us on [discord](https://discord.gg/SHVaVfV) if you have questions. Thanks.
