### ISSUE TITLE
Bump lib version

### ISSUE THREAD

**Issue by Igortorrente** [Auburn/FastNoise#62]
Can you bump the lib version to cover the fixes 92c5a68d23280660d634ba59fba791d722af0723 and 2fbd2b4ebf0f8735fcdec3bfe5c1e1c6a446dcf4?
I will reference this lib in a project that I'm working and would be nice to have a version number to put as dependency. Instead of commit hash number...

**Comment by Auburn** [comment]
Done

**Comment by Igortorrente** [comment]
Thanks!
